name: Get Date

on:
  workflow_call:
    outputs:
      year:
        description: The current year.
        value: ${{ jobs.get-date.outputs.year }}
      month:
        description: The current month.
        value: ${{ jobs.get-date.outputs.month }}
      day:
        description: The current day.
        value: ${{ jobs.get-date.outputs.day }}
      date:
        description: The current date (YYYY-mm-DD).
        value: ${{ jobs.get-date.outputs.date }}

jobs:
  get-date:
    name: Determine the Date
    runs-on: ubuntu-latest
    outputs:
      year: ${{ steps.get-date.outputs.year }}
      month: ${{ steps.get-date.outputs.month }}
      day: ${{ steps.get-date.outputs.day }}
      date: ${{ steps.get-date.outputs.date }}
    steps:
      - id: get-date
        name: Get the Date
        shell: bash
        run: |
          current_year=$(date -u "+%Y")
          current_month=$(date -u "+%m")
          current_day=$(date -u "+%d")
          current_date=${current_year}-${current_month}-${current_day}
          echo "::group::Current Date is ${current_date}"
          echo "year=${current_year}"
          echo "month=${current_month}"
          echo "day=${current_day}"
          echo "::endgroup::"
          echo "year=${current_year}" >> "$GITHUB_OUTPUT"
          echo "month=${current_month}" >> "$GITHUB_OUTPUT"
          echo "day=${current_day}" >> "$GITHUB_OUTPUT"
          echo "date=${current_date}" >> "$GITHUB_OUTPUT"
