name: Maven Verify

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: A prefix for artifact names.
        type: string
        required: true
      directory:
        description: The directory in which to run the build.
        type: string
        default: "."
      java-version:
        description: The version of Java to use.
        type: string
        default: 25
      year:
        description: The current year.
        type: string
        required: true
      month:
        description: The current month.
        type: string
        required: true
      day:
        description: The current day.
        type: string
        required: true

env: {}

jobs:
  build:
    name: Build
    permissions:
      contents: read
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ github.token }}
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - id: setup-java
        name: Set up Temurin JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin
          java-package: jdk
          overwrite-settings: false
      # The setup-java action builds a settings file, but we want a better one
      # that includes GitHub repositories across all projects for the owner.
      - id: create-settings-file
        name: Create Maven Settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          githubServer: true
          servers: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "username": "${{ github.actor }}",
                "password": "${{ github.token }}"
              }
            ]
          repositories: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "name": "GitHub ${{ github.repository_owner }}",
                "url": "https://maven.pkg.github.com/${{ github.repository_owner }}/packages",
                "snapshots": {"enabled": true}
              }
            ]
          pluginRepositories: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "name": "GitHub ${{ github.repository_owner }}",
                "url": "https://maven.pkg.github.com/${{ github.repository_owner }}/packages",
                "snapshots": {"enabled": true}
              }
            ]
      # The setup-java action populates the toolchains file, but it only uses
      # the new "marketing" version numbers.
      - id: create-toolchains-file
        name: Configure Maven Toolchains
        env:
          FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true
        uses: cactuslab/maven-toolchains-xml-action@v2
        with:
          toolchains: |
            [
              {"jdkVersion": "${{ steps.setup-java.outputs.version }}", "jdkHome": "${{ steps.setup-java.outputs.path }}"},
              {"jdkVersion": "1.${{ steps.setup-java.outputs.version }}", "jdkHome": "${{ steps.setup-java.outputs.path }}"}
            ]
      - name: Fetch Cached Maven Dependencies
        uses: actions/cache/restore@v5
        with:
          key: maven-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}
            maven-${{ inputs.year }}-${{ inputs.month }}
            maven-${{ inputs.year }}
            maven
          path: |
            ~/.m2/repository
      - name: Fetch Cached NVD Data
        uses: actions/cache/restore@v5
        with:
          key: owasp-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}
          restore-keys: |
            owasp-${{ inputs.year }}-${{ inputs.month }}
            owasp-${{ inputs.year }}
            owasp
          path: |
            ~/.m2/repository/org/owasp/dependency-check-data/
      - name: Clean
        run: mvn clean
      - name: Verify
        run: mvn verify
      - name: Site
        continue-on-error: true
        run: mvn site
      - name: Upload Artifacts
        uses: actions/upload-artifact@v7
        with:
          name: ${{ inputs.artifact-prefix }}-target
          path: ${{ inputs.directory }}/**/target/
  publish-test-results:
    name: Publish Test Results
    permissions:
      checks: write
    needs:
      - build
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-prefix }}-target
          path: ${{ inputs.directory }}/
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action/linux@v2
        if: (!cancelled())
        continue-on-error: true
        with:
          check_name: "Java Test Results"
          files: |
            ${{ inputs.directory }}/**/target/surefire-reports/TEST-*.xml
            ${{ inputs.directory }}/**/target/failsafe-reports/TEST-*.xml
          comment_mode: off
