name: Cache Maven Dependencies

on:
  workflow_call:
    inputs:
      directory:
        description: The directory in which to run the build.
        type: string
        default: "."
      java-version:
        description: The version of Java to use for initializing the Maven cache.
        type: string
        default: 25
      year:
        description: The current year.
        type: string
        required: true
      month:
        description: The current month.
        type: string
        required: true
      day:
        description: The current day.
        type: string
        required: true

env: {}

jobs:
  initialize-caches:
    name: Initialize Caches
    permissions:
      contents: read
      packages: read
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - id: setup-java
        name: Set up Temurin JDK ${{ inputs.java-version }}
        uses: actions/setup-java@v5
        with:
          java-version: ${{ inputs.java-version }}
          distribution: temurin
          java-package: jdk
          overwrite-settings: false
      # The setup-java action builds a settings file, but we want a better one
      # that includes GitHub repositories across all projects for the owner.
      - id: create-settings-file
        name: Create Maven Settings
        uses: s4u/maven-settings-action@v4.0.0
        with:
          githubServer: true
          servers: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "username": "${{ github.actor }}",
                "password": "${{ github.token }}"
              }
            ]
          repositories: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "name": "GitHub ${{ github.repository_owner }}",
                "url": "https://maven.pkg.github.com/${{ github.repository_owner }}/packages",
                "snapshots": {"enabled": true}
              }
            ]
          pluginRepositories: |
            [
              {
                "id": "github-${{ github.repository_owner }}",
                "name": "GitHub ${{ github.repository_owner }}",
                "url": "https://maven.pkg.github.com/${{ github.repository_owner }}/packages",
                "snapshots": {"enabled": true}
              }
            ]
      # The setup-java action populates the toolchains file, but it only uses
      # the new "marketing" version numbers.
      - id: create-toolchains-file
        name: Configure Maven Toolchains
        uses: cactuslab/maven-toolchains-xml-action@v2
        with:
          toolchains: |
            [
              {"jdkVersion": "${{ steps.setup-java.outputs.version }}", "jdkHome": "${{ steps.setup-java.outputs.path }}"},
              {"jdkVersion": "1.${{ steps.setup-java.outputs.version }}", "jdkHome": "${{ steps.setup-java.outputs.path }}"}
            ]
      # Store the entire local Maven repository as a GitHub cache.
      # This is stupid, but GitHub does not offer a non-stupid alternative.
      - name: Cache Maven Dependencies
        uses: actions/cache@v5
        continue-on-error: true
        with:
          key: maven-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            maven-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}
            maven-${{ inputs.year }}-${{ inputs.month }}
            maven-${{ inputs.year }}
            maven
          path: |
            ~/.m2/repository
      - name: Cache NVD Data
        uses: actions/cache@v5
        continue-on-error: true
        with:
          key: owasp-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}
          restore-keys: |
            owasp-${{ inputs.year }}-${{ inputs.month }}
            owasp-${{ inputs.year }}
            owasp
          path: |
            ~/.m2/repository/org/owasp/dependency-check-data/
      - name: Resolve Dependencies
        continue-on-error: true
        run: mvn dependency:go-offline
      - name: Resolve PGP Keys
        continue-on-error: true
        run: mvn pgpverify:go-offline
      - name: Update NVD Data
        continue-on-error: true
        run: mvn dependency-check:update-only
