name: NuGet Push

on:
  workflow_call:
    inputs:
      artifact-prefix:
        description: A prefix for artifact names.
        type: string
        default: "nuget"
      directory:
        description: The directory in which to run the build.
        type: string
        default: "."

jobs:
  setup:
    name: Push
    permissions:
      contents: read
      packages: write
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure GitHub Packages
        run: >-
          nuget sources add
          -Name GitHub
          -UserName ${{ github.actor }}
          -Password ${{ secrets.GITHUB_TOKEN }}
          -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          -NonInteractive
      - name: Download NuGet Artifact
        uses: actions/download-artifact@v8
        with:
          name: ${{ inputs.artifact-prefix }}-package
          path: ${{ inputs.directory }}
      - name: Push
        run: >-
          nuget push *.nupkg
          -ApiKey ${{ secrets.GITHUB_TOKEN }}
          -Source GitHub
          -NonInteractive
