name: Cache NuGet Dependencies

on:
  workflow_call:
    inputs:
      directory:
        description: The directory in which to run the build.
        type: string
        default: "."
      solution-file:
        description: The name of the solution file.
        type: string
        required: true
      year:
        description: The current year.
        type: string
        required: true
      month:
        description: The current month.
        type: string
        required: true
      day:
        description: The current day.
        type: string
        required: true

jobs:
  setup:
    name: Initialize Package Cache
    permissions:
      contents: read
      packages: read
    runs-on: windows-2022
    defaults:
      run:
        working-directory: ${{ inputs.directory }}
    steps:
      - name: Checkout
        uses: actions/checkout@v6
      - name: Configure GitHub Packages
        run: >-
          nuget sources add
          -Name GitHub
          -UserName ${{ github.actor }}
          -Password ${{ secrets.GITHUB_TOKEN }}
          -Source https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json
          -NonInteractive
      - name: Cache NuGet Dependencies
        uses: actions/cache@v5
        continue-on-error: true
        with:
          key: nuget-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}-${{ hashFiles('**/*.*proj') }}
          restore-keys: |
            nuget-${{ inputs.year }}-${{ inputs.month }}-${{ inputs.day }}
            nuget-${{ inputs.year }}-${{ inputs.month }}
            nuget-${{ inputs.year }}
            nuget
          path: ~/.nuget/packages/
      - name: Restore
        run: nuget restore ${{ inputs.solution-file }} -NonInteractive
